# Generated by Django 3.0.6 on 2020-07-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('user', models.CharField(max_length=127)),
                ('img', models.URLField()),
            ],
        ),
    ]
